=== dgisolfi/CMPT308-Gisolfi/Lab2/Customers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Customers" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Customers">
<xsd:annotation>
<xsd:appinfo/>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="CNum" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="4"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="CustName" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="20"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Priority" minOccurs="1" od:jetType="integer" od:sqlSType="smallint" od:nonNullable="yes" type="xsd:short"/>
<xsd:element name="Hometown" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="25"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== dgisolfi/CMPT308-Gisolfi/Lab2/Customers.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Customers.xsd" generated="2017-09-18T10:26:55">
<Customers>
<CNum>C100</CNum>
<CustName>Sheldon</CustName>
<Priority>20</Priority>
<Hometown>Houston</Hometown>
</Customers>
<Customers>
<CNum>C200</CNum>
<CustName>Leonard</CustName>
<Priority>10</Priority>
<Hometown>Boston</Hometown>
</Customers>
<Customers>
<CNum>C300</CNum>
<CustName>Raj</CustName>
<Priority>30</Priority>
<Hometown>Boston</Hometown>
</Customers>
<Customers>
<CNum>C400</CNum>
<CustName>Penny</CustName>
<Priority>20</Priority>
<Hometown>Houston</Hometown>
</Customers>
<Customers>
<CNum>C500</CNum>
<CustName>Howard</CustName>
<Priority>30</Priority>
<Hometown>LosAngeles</Hometown>
</Customers>
</dataroot>
