=== dgisolfi/CMPT308-Gisolfi/Lab2/Dishes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Dishes" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Dishes">
<xsd:annotation>
<xsd:appinfo/>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="DNum" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="4"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="DishName" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="20"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="ListPrice" minOccurs="1" od:jetType="double" od:sqlSType="float" od:nonNullable="yes" type="xsd:double"/>
<xsd:element name="Calories" minOccurs="1" od:jetType="longinteger" od:sqlSType="int" od:nonNullable="yes" type="xsd:int"/>
<xsd:element name="CityOfOrigin" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="25"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== dgisolfi/CMPT308-Gisolfi/Lab2/Dishes.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Dishes.xsd" generated="2017-09-18T10:27:23">
<Dishes>
<DNum>D1</DNum>
<DishName>BBQbaconBurger</DishName>
<ListPrice>9.99</ListPrice>
<Calories>1200</Calories>
<CityOfOrigin>Houston</CityOfOrigin>
</Dishes>
<Dishes>
<DNum>D2</DNum>
<DishName>MeeKrob</DishName>
<ListPrice>24.99</ListPrice>
<Calories>600</Calories>
<CityOfOrigin>Boston</CityOfOrigin>
</Dishes>
<Dishes>
<DNum>D3</DNum>
<DishName>ChickenSatay</DishName>
<ListPrice>19.99</ListPrice>
<Calories>800</Calories>
<CityOfOrigin>NewOrleans</CityOfOrigin>
</Dishes>
<Dishes>
<DNum>D4</DNum>
<DishName>CashewChicken</DishName>
<ListPrice>9.99</ListPrice>
<Calories>1500</Calories>
<CityOfOrigin>Houston</CityOfOrigin>
</Dishes>
<Dishes>
<DNum>D5</DNum>
<DishName>BurritoGrande</DishName>
<ListPrice>9.99</ListPrice>
<Calories>1000</Calories>
<CityOfOrigin>Boston</CityOfOrigin>
</Dishes>
<Dishes>
<DNum>D6</DNum>
<DishName>SteamedDumpling</DishName>
<ListPrice>9.99</ListPrice>
<Calories>400</Calories>
<CityOfOrigin>Houston</CityOfOrigin>
</Dishes>
</dataroot>
