=== dgisolfi/CMPT308-Gisolfi/Lab2/Orders.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Orders" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Orders">
<xsd:annotation>
<xsd:appinfo/>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="CNum" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="4"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="DNum" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="4"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="RNum" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="4"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Quant" minOccurs="1" od:jetType="integer" od:sqlSType="smallint" od:nonNullable="yes" type="xsd:short"/>
<xsd:element name="Price" minOccurs="1" od:jetType="double" od:sqlSType="float" od:nonNullable="yes" type="xsd:double"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== dgisolfi/CMPT308-Gisolfi/Lab2/Orders.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Orders.xsd" generated="2017-09-18T10:27:33">
<Orders>
<CNum>C100</CNum>
<DNum>D1</DNum>
<RNum>R10</RNum>
<Quant>2</Quant>
<Price>8.99</Price>
</Orders>
<Orders>
<CNum>C100</CNum>
<DNum>D1</DNum>
<RNum>R40</RNum>
<Quant>7</Quant>
<Price>9.99</Price>
</Orders>
<Orders>
<CNum>C200</CNum>
<DNum>D3</DNum>
<RNum>R10</RNum>
<Quant>4</Quant>
<Price>16.99</Price>
</Orders>
<Orders>
<CNum>C200</CNum>
<DNum>D3</DNum>
<RNum>R20</RNum>
<Quant>2</Quant>
<Price>15.99</Price>
</Orders>
<Orders>
<CNum>C200</CNum>
<DNum>D3</DNum>
<RNum>R30</RNum>
<Quant>2</Quant>
<Price>17.99</Price>
</Orders>
<Orders>
<CNum>C200</CNum>
<DNum>D3</DNum>
<RNum>R40</RNum>
<Quant>5</Quant>
<Price>19.99</Price>
</Orders>
<Orders>
<CNum>C200</CNum>
<DNum>D3</DNum>
<RNum>R50</RNum>
<Quant>6</Quant>
<Price>18.99</Price>
</Orders>
<Orders>
<CNum>C200</CNum>
<DNum>D3</DNum>
<RNum>R60</RNum>
<Quant>4</Quant>
<Price>19.99</Price>
</Orders>
<Orders>
<CNum>C200</CNum>
<DNum>D3</DNum>
<RNum>R70</RNum>
<Quant>8</Quant>
<Price>15.99</Price>
</Orders>
<Orders>
<CNum>C200</CNum>
<DNum>D5</DNum>
<RNum>R20</RNum>
<Quant>1</Quant>
<Price>8.99</Price>
</Orders>
<Orders>
<CNum>C300</CNum>
<DNum>D3</DNum>
<RNum>R10</RNum>
<Quant>2</Quant>
<Price>16.99</Price>
</Orders>
<Orders>
<CNum>C300</CNum>
<DNum>D4</DNum>
<RNum>R20</RNum>
<Quant>5</Quant>
<Price>22.99</Price>
</Orders>
<Orders>
<CNum>C400</CNum>
<DNum>D6</DNum>
<RNum>R30</RNum>
<Quant>3</Quant>
<Price>4.99</Price>
</Orders>
<Orders>
<CNum>C400</CNum>
<DNum>D6</DNum>
<RNum>R70</RNum>
<Quant>3</Quant>
<Price>2.99</Price>
</Orders>
<Orders>
<CNum>C500</CNum>
<DNum>D1</DNum>
<RNum>R40</RNum>
<Quant>1</Quant>
<Price>9.99</Price>
</Orders>
<Orders>
<CNum>C500</CNum>
<DNum>D2</DNum>
<RNum>R20</RNum>
<Quant>2</Quant>
<Price>23.99</Price>
</Orders>
<Orders>
<CNum>C500</CNum>
<DNum>D2</DNum>
<RNum>R40</RNum>
<Quant>1</Quant>
<Price>24.99</Price>
</Orders>
<Orders>
<CNum>C500</CNum>
<DNum>D3</DNum>
<RNum>R40</RNum>
<Quant>2</Quant>
<Price>19.99</Price>
</Orders>
<Orders>
<CNum>C500</CNum>
<DNum>D4</DNum>
<RNum>R40</RNum>
<Quant>8</Quant>
<Price>23.99</Price>
</Orders>
<Orders>
<CNum>C500</CNum>
<DNum>D5</DNum>
<RNum>R40</RNum>
<Quant>4</Quant>
<Price>8.99</Price>
</Orders>
<Orders>
<CNum>C500</CNum>
<DNum>D5</DNum>
<RNum>R50</RNum>
<Quant>5</Quant>
<Price>8.99</Price>
</Orders>
<Orders>
<CNum>C500</CNum>
<DNum>D5</DNum>
<RNum>R70</RNum>
<Quant>1</Quant>
<Price>9.99</Price>
</Orders>
<Orders>
<CNum>C500</CNum>
<DNum>D6</DNum>
<RNum>R20</RNum>
<Quant>2</Quant>
<Price>1.99</Price>
</Orders>
<Orders>
<CNum>C500</CNum>
<DNum>D6</DNum>
<RNum>R40</RNum>
<Quant>5</Quant>
<Price>3.99</Price>
</Orders>
</dataroot>
