=== dgisolfi/CMPT308-Gisolfi/Lab2/Restaurants.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Restaurants" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Restaurants">
<xsd:annotation>
<xsd:appinfo/>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="RNum" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="4"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="RestaurantName" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="20"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="HQLocation" minOccurs="1" od:jetType="text" od:sqlSType="nvarchar" od:nonNullable="yes">
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="25"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== dgisolfi/CMPT308-Gisolfi/Lab2/Restaurants.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Restaurants.xsd" generated="2017-09-18T10:27:43">
<Restaurants>
<RNum>R10</RNum>
<RestaurantName>SiamPalace</RestaurantName>
<HQLocation>Boston</HQLocation>
</Restaurants>
<Restaurants>
<RNum>R20</RNum>
<RestaurantName>SzechuanPalace</RestaurantName>
<HQLocation>NewOrleans</HQLocation>
</Restaurants>
<Restaurants>
<RNum>R30</RNum>
<RestaurantName>GoldenDragon</RestaurantName>
<HQLocation>LosAngeles</HQLocation>
</Restaurants>
<Restaurants>
<RNum>R40</RNum>
<RestaurantName>CheesecakeFactory</RestaurantName>
<HQLocation>LosAngeles</HQLocation>
</Restaurants>
<Restaurants>
<RNum>R50</RNum>
<RestaurantName>BombayPalace</RestaurantName>
<HQLocation>Houston</HQLocation>
</Restaurants>
<Restaurants>
<RNum>R60</RNum>
<RestaurantName>SoupPlantation</RestaurantName>
<HQLocation>Poughkeepsie</HQLocation>
</Restaurants>
<Restaurants>
<RNum>R70</RNum>
<RestaurantName>Giacomos</RestaurantName>
<HQLocation>Houston</HQLocation>
</Restaurants>
</dataroot>
